ci: fix GPU benches (#857)
https://github.com/lurk-lab/lurk-rs/actions/runs/6773544195/job/18408644257

This resulted in:
```
thread 'main' panicked at benches/fibonacci_lem.rs:67:33:
not yet implemented
```
This makes sure the `todo!()` at this line is no longer there to be found.